language: python
python:
  - 3.9
  - 3.8
  - 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: phillipsj
  password:
    secure: IgO1i1763t78ncRHdbKAwjr8Lnzj9m8+gfoi7Srq+TM29yVgNlQRCAYeE0ZDj739idWtXZjwLKkJmzh34axbCsTqqmWXDb7W5kkPNGsmAMmMAENeV/XkvG7pbN7fYcxY+8kpMvBoQK80s7ZRKiXda/S0uFP99cROk4o4t1zDbVXRoM1/uHrCQr+HVW6r4M5evbuy7SKWamjC2TPC6wSHvd+sY+Y26Xagt0QwE1TXq4zxy+FjsRtWJphMv9z0C8ocgVT5AR/ZS5L2d/q8IYqVPsWbjenkHhXy+gYDHgDTzPFqTobKzMIv61S7jq+TKvWMzUfHA9SdtXxYHY2KGrnTqDThRAHLdtjQV9gDEexnDpLIaDMJf/5XmEJLyPdwGtRL24beBDY9I2VsqgLuGVS1KepKJBEKe4MyrNIQmCxYKJFg6VfitDV6ylwKa2WlH1Xq5WCpYd3yre/NXoN7pXbxdIOEp3SxM6qbPCGw75ZDJUXuqYzCMU90V35Mnn1m1BgcygBa/6DnupMW+3dc3XA84FIGkN0MHGqPmhMoY7AJzniMh8XLNkbl4X3ZHlEZ7YR0kBRCspT037n4DBDXgVdRm/FTZgxm0GtPeOgwmkmP09bnd8HxrT5MAf0nazd8o9z6F+0WXPW8JwTljkLnfePr1hj7LoJ+e6NS+aKhOfr62Q0=
  on:
    tags: true
    repo: blueghostlabs/poshpy
    python: 3.8
